export const SEARCH_ENTITY = 'SEARCH_ENTITY';

export const SET_ENTITY_IDS = 'SET_ENTITY_IDS';

export const SET_ENTITY_CURRENT_PAGE = 'SET_ENTITY_CURRENT_PAGE';
export const SET_ENTITY_PAGE_SIZE = 'SET_ENTITY_PAGE_SIZE';
export const SET_ENTITY_PER_PAGE = 'SET_ENTITY_PER_PAGE';
export const SET_ENTITY_TOTAL_ELEMENTS = 'SET_ENTITY_TOTAL_ELEMENTS';
export const SET_ENTITY_TOTAL_PAGES = 'SET_ENTITY_TOTAL_PAGES';

export const SEARCH_ENTITY_SUCCESS = 'SEARCH_ENTITY_SUCCESS';
export const SEARCH_ENTITY_FAILURE = 'SEARCH_ENTITY_FAILURE';
