export const SEARCH_ENTITY = 'SEARCH_ENTITY';

export const SET_ENTITY_IDS = 'SET_ENTITY_IDS';

export const SEARCH_ENTITY_SUCCESS = 'SEARCH_ENTITY_SUCCESS';
export const SEARCH_ENTITY_FAILURE = 'SEARCH_ENTITY_FAILURE';
