export const READ_ENTITY = 'READ_ENTITY';
export const ENTITY_RECEIVED = 'ENTITY_RECEIVED';

export const CREATE_ENTITY = 'CREATE_ENTITY';
export const ENTITY_SAVED = 'ENTITY_SAVED';

export const UPDATE_ENTITY = 'UPDATE_ENTITY';
export const ENTITY_UPDATED = 'ENTITY_UPDATED';

export const DELETE_ENTITY = 'DELETE_ENTITY';
export const ENTITY_DELETED = 'ENTITY_DELETED';

export const GENERATE_ENTITY_REPORT = 'GENERATE_ENTITY_REPORT';
