export const ADD_ENTITIES = 'ADD_ENTITIES';

export const CREATE_ENTITY = 'CREATE_ENTITY';

export const CREATE_ENTITY_FAILURE = 'CREATE_ENTITY_FAILURE';
export const CREATE_ENTITY_SUCCESS = 'CREATE_ENTITY_SUCCESS';
