export const CREATE_ENTITIES = 'CREATE_ENTITIES';
export const REQUEST_ENTITIES = 'REQUEST_ENTITIES';
export const FETCHING_ENTITIES = 'FETCHING_ENTITIES';

export const CHANGE_PAGE_PREV_ENTITIES = 'CHANGE_PAGE_PREV_ENTITIES';
export const CHANGE_PAGE_NEXT_ENTITIES = 'CHANGE_PAGE_NEXT_ENTITIES';

export const REQUEST_SUCCESS_ENTITIES = 'REQUEST_SUCCESS_ENTITIES';
export const REQUEST_FAILURE_ENTITIES = 'REQUEST_FAILURE_ENTITIES';
